import { MainLayout } from '@/layouts/main-layout/main-layout'
import './globalStyles.scss'

export const metadata = {
    title: 'Sách hay',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    )
}
