import './global-styles.scss'

export const metadata = {
    title: 'Sách hay',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
